### ISSUE TITLE
Use of this version exposes a server-side full directory structure to the client-side

### ISSUE THREAD

**Issue by DaveBrad** [daverogers/jQueryFileTree#10]
Hi, The removal of the $root (#3 fix) basically exposes the server-side directory to the client-side. Just run with a debug (firefox firebug) and you can see from root on down, thus allowing directory mining of web site's file sytem, including any shared hosting sites (depending on hosting management).

Below is a more secure approach to using Tree File, by introducing $treeFileRoot so only directories below the tree-file-root are visible, and no server-side file paths are exposed on the client-side when using debuggers.

...
    <?php
    // IMPORTANT: $fileTreeRoot needs to be set for this script to work (see below)
    //
    // THIS IS A BASE FILE, it is strongly advised that you copy this file to
    // a place on your webpages with a different name, and then use the different
    // name as the 'script: scriptname' in your webpage that displays the
    // tree file.
    //
    // Once copied you may remove most comments from the script so as to save
    // some space and processing time
    /**
     * jQuery File Tree PHP Connector
     *
     * Version 1.1.0
     *
     * @author - Cory S.N. LaViska A Beautiful Site (http://abeautifulsite.net/)
     * @author - Dave Rogers - https://github.com/daverogers/jQueryFileTree
     *        
     *         History:
     *        
     *         1.1.0 - adding multiSelect (checkbox) support (08/22/2014)
     *         1.0.2 - fixes undefined 'dir' error - by itsyash (06/09/2014)
     *         1.0.1 - updated to work with foreign characters in directory/file names (12 April 2008)
     *         1.0.0 - released (24 March 2008)
     *        
     *         Output a list of files for jQuery File Tree
     */
    
    // must be referred to this file from within host system
    // and not via direct access (book mark) as there is sensitive $_POST information
    //
    // This assists in preventing users from book marking this page or attempting
    // to access directly and having the invoker getting access to server
    // information.
    if (! array_key_exists ( 'HTTP_REFERER', $_SERVER )) {
    	// redirect to the hosts root page
    	// WARNING WARNING WARNING -- make sure your site has an index.html/index.php
    	// so as to except this redirect
    	header ( "Location: http://" . $_SERVER ['HTTP_HOST'] );
    	die ();
    }
    
    /**
     * USER USER USER USER please set me
     */
    $fileTreeRoot;
     /**
     * $fileTreeRoot provides the root within the server where files are to
     * be displayed from.
     *
     * Typically this will be some thing like:
     * 1) $fileTreeRoot = $_SERVER['DOCUMENT_ROOT'] . 'public';
     * 2) $fileTreeRoot = $_SERVER['DOCUMENT_ROOT'] . 'public/files';
     *
     * [ 'public' and 'files' are directory paths in your file structure
     * ---- do not terminate with '/' ]
     *
     * When combined with the "root: /" setting of the archiecture will
     * result in all files under 'public/' or 'public/files/' being
     * displayed in the tree.
     *
     * If you set $fileTreeRoot = '/'; -----> all the machines files will be exposed
     * and/or using debug users can determine your server's directory structure.
     * ---------- [BIG SECURITY ISSUE] --------
     */
    
    // When the $fileTreeRoot has been appropriately set
    // the following code may be commented out (or deleted)
    if (! isset ( $fileTreeRoot )) {
    	$fileMe = __FILE__;
    	echo "<p>Need to configure file-tree-root variable in: $fileMe</p>";
    	exit ();
    }
     
    $_POST ['dir'] = urldecode ( (isset ( $_POST ['dir'] ) ? $_POST ['dir'] : null) );
    
    // set checkbox if multiSelect set to true
    $checkbox = (isset ( $_POST ['multiSelect'] ) && $_POST ['multiSelect'] == 'true') ? "<input     type='checkbox' />" : null;

    // restrict the displayed directory to be below the file-tree-root
    // but need to process files and scans with asolute full paths
    //
    // within this PHP file the full paths are confined to the server and
    // client users cannot see them
    $postDir = $fileTreeRoot . $_POST ['dir'];
    
    // when processing via scandir will be created absolute paths to files
    // this information should NOT be allowed to go to the client
   $fileTreeRootLen = strlen ( $fileTreeRoot );
    
    if (file_exists ( $postDir )) {
	$files = scandir ( $postDir );
	
	// base-dir is the path that is below the $fileTreeRoot path
	// which concatenate with $file will be the relative path information
	// sent to the client
	$baseDir = substr ( $postDir, $fileTreeRootLen );
	
	natcasesort ( $files );
	
	if (count ( $files ) > 2) { // The 2 accounts for . and ..
		echo "<ul class='jqueryFileTree'>";
		// All dirs
		foreach ( $files as $file ) {
			// full path info for file_exists (server-side data only)
			$postDir_File = $postDir . $file;
			
			if (file_exists ( $postDir_File ) && $file != '.' && $file != '..' && is_dir ( $postDir_File )) {
				// client side info is relative to $treeFIleRoot
				$htmlBaseFile = htmlentities ( $baseDir . $file );
				$htmlFile = htmlentities ( $file );
				
				ECHO <<<DIRCOLLAPSE
<li class='directory collapsed'>{$checkbox}<a href='#' rel='$htmlBaseFile/'>$htmlFile</a></li>
DIRCOLLAPSE;
				
				// if you don't like heredocs use
				// echo "<li class='directory collapsed'>";
				// echo "{$checkbox}<a href='#' rel='" . htmlentities ( $baseDir . $file) . "/'>" . htmlentities ( $file ) . "</a></li>";
			}
		}
		// All files
		foreach ( $files as $file ) {
			if (file_exists ( $postDir_File ) && $file != '.' && $file != '..' && ! is_dir ( $postDir_File )) {
				$ext = preg_replace ( '/^.*\./', '', $file );
				
				// client side info is relative to $treeFIleRoot
				$htmlBaseFile = htmlentities ( $baseDir . $file );
				$htmlFile = htmlentities ( $file );
				
				ECHO <<<DIREXT
<li class='file ext_{$ext}'>
{$checkbox}<a href='#' rel='$htmlBaseFile'>$htmlFile</a></li>
DIREXT;
				
				// if you don't like heredocs use
				// echo "<li class='file ext_{$ext}'>{$checkbox}<a href='#' rel='" . htmlentities ( $baseDir . $file ) . "'>" . htmlentities ( $file ) . "</a></li>";
			}
		}
		echo "</ul>";
	}
}

?>

...

**Comment by DaveBrad** [comment]
Sorry about that, but GITHUB hasn't got a cod interface/markup that works with html or php. Changed   the greater-than and less-than to &tl and &gt so the code is below.


<pre>

&lt;?php
// IMPORTANT: $fileTreeRoot needs to be set for this script to work (see below)
//
// THIS IS A BASE FILE, it is strongly advised that you copy this file to
// a place on your webpages with a different name, and then use the different
// name as the 'script: scriptname' in your webpage that displays the
// tree file.
//
// Once copied you may remove most comments from the script so as to save
// some space and processing time
/**
 * jQuery File Tree PHP Connector
 *
 * Version 1.1.0
 *
 * @author - Cory S.N. LaViska A Beautiful Site (http://abeautifulsite.net/)
 * @author - Dave Rogers - https://github.com/daverogers/jQueryFileTree
 *        
 *         History:
 *        
 *         1.1.0 - adding multiSelect (checkbox) support (08/22/2014)
 *         1.0.2 - fixes undefined 'dir' error - by itsyash (06/09/2014)
 *         1.0.1 - updated to work with foreign characters in directory/file names (12 April 2008)
 *         1.0.0 - released (24 March 2008)
 *        
 *         Output a list of files for jQuery File Tree
 */

// must be referred to this file from within host system
// and not via direct access (book mark) as there is sensitive $_POST information
//
// This assists in preventing users from book marking this page or attempting
// to access directly and having the invoker getting access to server
// information.
if (! array_key_exists ( 'HTTP_REFERER', $_SERVER )) {
	// redirect to the hosts root page
	// WARNING WARNING WARNING -- make sure your site has an index.html/index.php
	// so as to except this redirect
	header ( "Location: http://" . $_SERVER ['HTTP_HOST'] );
	die ();
}

/**
 * USER USER USER USER please set me
 */
$fileTreeRoot;
/**
 * $fileTreeRoot provides the root within the server where files are to
 * be displayed from.
 *
 * Typically this will be some thing like:
 * 1) $fileTreeRoot = $_SERVER['DOCUMENT_ROOT'] . 'public';
 * 2) $fileTreeRoot = $_SERVER['DOCUMENT_ROOT'] . 'public/files';
 *
 * [ 'public' and 'files' are directory paths in your file structure
 * ---- do not terminate with '/' ]
 *
 * When combined with the "root: /" setting of the archiecture will
 * result in all files under 'public/' or 'public/files/' being
 * displayed in the tree.
 *
 * If you set $fileTreeRoot = '/'; -----> all the machines files will be exposed
 * and/or using debug users can determine your server's directory structure.
 * ---------- [BIG SECURITY ISSUE] --------
 */

// When the $fileTreeRoot has been appropriately set
// the following code may be commented out (or deleted)
if (! isset ( $fileTreeRoot )) {
	$fileMe = __FILE__;
	echo "&lt;p&gt;Need to configure file-tree-root variable in: $fileMe&lt;/p&gt;";
	exit ();
}

$_POST ['dir'] = urldecode ( (isset ( $_POST ['dir'] ) ? $_POST ['dir'] : null) );

// set checkbox if multiSelect set to true
$checkbox = (isset ( $_POST ['multiSelect'] ) && $_POST ['multiSelect'] == 'true') ? "&lt;nput type='checkbox' /&gt;" : null;

// restrict the displayed directory to be below the file-tree-root
// but need to process files and scans with absolute full paths
//
// within this PHP file the full paths are confined to the server and
// client users cannot see them
$postDir = $fileTreeRoot . $_POST ['dir'];

// when processing via scandir will be created absolute paths to files
// this information should NOT be allowed to go to the client
$fileTreeRootLen = strlen ( $fileTreeRoot );

if (file_exists ( $postDir )) {
	$files = scandir ( $postDir );
	
	// base-dir is the path that is below the $fileTreeRoot path
	// which concatenate with $file will be the relative path information
	// sent to the client
	$baseDir = substr ( $postDir, $fileTreeRootLen );
	
	natcasesort ( $files );
	
	if (count ( $files ) &gt; 2) { // The 2 accounts for . and ..
		echo "&lt;ul class='jqueryFileTree'&gt;";
		// All dirs
		foreach ( $files as $file ) {
			// full path info for file_exists (server-side data only)
			$postDir_File = $postDir . $file;
			
			if (file_exists ( $postDir_File ) && $file != '.' && $file != '..' && is_dir ( $postDir_File )) {
				// client side info is relative to $treeFIleRoot
				$htmlBaseFile = htmlentities ( $baseDir . $file );
				$htmlFile = htmlentities ( $file );
				
				ECHO <<<DIRCOLLAPSE
&lt;li class='directory collapsed'>{$checkbox}&lt;a href='#' rel='$htmlBaseFile/'&gt;$htmlFile&lt;/a&gt;&lt;/li&gt;
DIRCOLLAPSE;
				
				// if you don't like heredocs use
				// echo "&lt;li class='directory collapsed'&gt;";
				// echo "{$checkbox}&lt;a href='#' rel='" . htmlentities ( $baseDir . $file) . "/'&gt;" . htmlentities ( $file ) . "&lt;/a&gt;&lt;/li&gt;";
			}
		}
		// All files
		foreach ( $files as $file ) {
			if (file_exists ( $postDir_File ) && $file != '.' && $file != '..' && ! is_dir ( $postDir_File )) {
				$ext = preg_replace ( '/^.*\./', '', $file );
				
				// client side info is relative to $treeFIleRoot
				$htmlBaseFile = htmlentities ( $baseDir . $file );
				$htmlFile = htmlentities ( $file );
				
				ECHO <<<DIREXT
<li class='file ext_{$ext}'>
{$checkbox}<a href='#' rel='$htmlBaseFile'>$htmlFile</a></li>
DIREXT;
				
				// if you don't like heredocs use
				// echo "&lt;li class='file ext_{$ext}'&gt;{$checkbox}&lt;a href='#' rel='" . htmlentities ( $baseDir . $file ) . "'&gt;" . htmlentities ( $file ) . "&lt;/a&gt;&lt;/li&gt;";
			}
		}
		echo "&lt;/ul&gt;";
	}
}

?&gt;

</pre>

**Comment by daverogers** [comment]
Thanks. I didn't give this any thought when I removed $root to fix that undefined error (I don't use this example script, but it's important to provide good code for users who want to copy/paste it into their project). I folded most of your ideas into the existing code.

**Comment by DaveBrad** [comment]
Thanks for listening and your changes look good and clean. 

Since then I've expanded on your stuff to have three checkboxes with flow-through to perform data changes on a SQL database that is securely contained on the server-side. Also, applied the file tree to a dictionary of words, makes things neat.

Some thanks again and for bringing new life to this neat "application".
